## Basics

In [2]:
print("Hello")
print('Hello')
print("Hello",5)
print("Hello" + str(5))

Hello
Hello
Hello 5
Hello5


In [3]:
2+3

5

In [4]:
a = 5
type(a)

int

In [5]:
a = "hello"
type(a)

str

In [6]:
b = 10.4
type(b)

float

In [7]:
condition = 1
while condition < 10 :
    print(condition)
    condition += 1

1
2
3
4
5
6
7
8
9


In [8]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9


In [9]:
x = 6
if x == 5:
    print(x)
else:
    print("Not x")

Not x


## Function

In [10]:
def example():
    print("this will run")
    z = 3 + 9
    print(z)

In [11]:
example()

this will run
12


In [12]:
def add(num1, num2):
    answer = num1 + num2
    return answer

In [13]:
add(5, 6)

11

## File Operations

In [14]:
text = "Sample text\nNew line!"
savefile = open('examplefile.txt', 'w') # w, r, a
savefile.write(text)
savefile.close()

In [15]:
append = "\nnew info"
appendfile = open('examplefile.txt', 'a')
appendfile.write(append)
appendfile.close()

In [16]:
readme = open('examplefile.txt', 'r')
print(readme.read())
readme.close()

Sample text
New line!
new info


## Collections

### list

In [17]:
x = [1, 2, 4 ,5 , 6, 9, 7, 8, 3]
x

[1, 2, 4, 5, 6, 9, 7, 8, 3]

In [18]:
x.insert(2,55)
x

[1, 2, 55, 4, 5, 6, 9, 7, 8, 3]

In [19]:
x.append(10)
x

[1, 2, 55, 4, 5, 6, 9, 7, 8, 3, 10]

In [20]:
x.remove(6)
x

[1, 2, 55, 4, 5, 9, 7, 8, 3, 10]

In [21]:
x.sort()
x

[1, 2, 3, 4, 5, 7, 8, 9, 10, 55]

In [22]:
x.reverse()
x

[55, 10, 9, 8, 7, 5, 4, 3, 2, 1]

In [23]:
x[2:5]

[9, 8, 7]

### Dictionary

In [24]:
exDict = {'Jack': 15, 'Bob': 21, 'Kevin': 17}

In [25]:
exDict.keys()

dict_keys(['Kevin', 'Bob', 'Jack'])

In [26]:
exDict.values()

dict_values([17, 21, 15])

In [27]:
exDict['Jack']

15

In [28]:
exDict1 = {'Jack': [15, 'black', 'NW']}

In [29]:
exDict1['Jack'][1]

'black'

## Pandas

In [30]:
import pandas as pd

In [31]:
web_stats = {
    'Day' : [1,2,3,4,5],
    'Visitors' : [42,44,45,46,48],
    'Bounce' : [65,57,58,59,80]
}

In [32]:
df = pd.DataFrame(web_stats)
df.head()

Bounce  Day  Visitors
0      65    1        42
1      57    2        44
2      58    3        45
3      59    4        46
4      80    5        48

In [34]:
employee_df = pd.read_excel('employees.xlsx', sheet_name='Sheet1')
employee_df.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          101      Neena   Kochhar  NKOCHHAR  515.123.4568 1989-09-21   
1          102        Lex   De Haan   LDEHAAN  515.123.4569 1993-01-13   
2          103  Alexander    Hunold   AHUNOLD  590.423.4567 1990-01-03   
3          104      Bruce     Ernst    BERNST  590.423.4568 1991-05-21   
4          105      David    Austin   DAUSTIN  590.423.4569 1997-06-25   

    JOB_ID  SALARY  COMMISSION_PCT  MANAGER_ID  DEPARTMENT_ID  
0    AD_VP   17000             NaN         100           90.0  
1    AD_VP   17000             NaN         100           90.0  
2  IT_PROG    9000             NaN         102           60.0  
3  IT_PROG    6000             NaN         103           60.0  
4  IT_PROG    4800             NaN         103           60.0

In [35]:
employee_df.columns

Index(['EMPLOYEE_ID', 'FIRST_NAME', 'LAST_NAME', 'EMAIL', 'PHONE_NUMBER',
       'HIRE_DATE', 'JOB_ID', 'SALARY', 'COMMISSION_PCT', 'MANAGER_ID',
       'DEPARTMENT_ID'],
      dtype='object')

In [36]:
employee_df = employee_df.drop("COMMISSION_PCT", axis=1)
employee_df.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME     EMAIL  PHONE_NUMBER  HIRE_DATE  \
0          101      Neena   Kochhar  NKOCHHAR  515.123.4568 1989-09-21   
1          102        Lex   De Haan   LDEHAAN  515.123.4569 1993-01-13   
2          103  Alexander    Hunold   AHUNOLD  590.423.4567 1990-01-03   
3          104      Bruce     Ernst    BERNST  590.423.4568 1991-05-21   
4          105      David    Austin   DAUSTIN  590.423.4569 1997-06-25   

    JOB_ID  SALARY  MANAGER_ID  DEPARTMENT_ID  
0    AD_VP   17000         100           90.0  
1    AD_VP   17000         100           90.0  
2  IT_PROG    9000         102           60.0  
3  IT_PROG    6000         103           60.0  
4  IT_PROG    4800         103           60.0

In [37]:
employee_df['EMPLOYEE_ID']

0      101
1      102
2      103
3      104
4      105
5      106
6      107
7      108
8      109
9      110
10     111
11     112
12     113
13     114
14     115
15     116
16     117
17     118
18     119
19     120
20     121
21     122
22     123
23     124
24     125
25     126
26     127
27     128
28     129
29     130
      ... 
76     177
77     178
78     179
79     180
80     181
81     182
82     183
83     184
84     185
85     186
86     187
87     188
88     189
89     190
90     191
91     192
92     193
93     194
94     195
95     196
96     197
97     198
98     199
99     200
100    201
101    202
102    203
103    204
104    205
105    206
Name: EMPLOYEE_ID, Length: 106, dtype: int64

In [38]:
employee_df[['EMPLOYEE_ID', 'FIRST_NAME']]

EMPLOYEE_ID   FIRST_NAME
0            101        Neena
1            102          Lex
2            103    Alexander
3            104        Bruce
4            105        David
5            106        Valli
6            107        Diana
7            108        Nancy
8            109       Daniel
9            110         John
10           111       Ismael
11           112  Jose Manuel
12           113         Luis
13           114          Den
14           115    Alexander
15           116       Shelli
16           117        Sigal
17           118          Guy
18           119        Karen
19           120      Matthew
20           121         Adam
21           122        Payam
22           123       Shanta
23           124        Kevin
24           125        Julia
25           126        Irene
26           127        James
27           128       Steven
28           129        Laura
29           130        Mozhe
..           ...          ...
76           177         Jack
77           178    Kimberely
78           179      Charles
79           180      Winston
80           181         Jean
81           182       Martha
82           183       Girard
83           184      Nandita
84           185       Alexis
85           186        Julia
86           187      Anthony
87           188        Kelly
88           189     Jennifer
89           190      Timothy
90           191      Randall
91           192        Sarah
92           193      Britney
93           194       Samuel
94           195        Vance
95           196        Alana
96           197        Kevin
97           198       Donald
98           199      Douglas
99           200     Jennifer
100          201      Michael
101          202          Pat
102          203        Susan
103          204      Hermann
104          205      Shelley
105          206      William

[106 rows x 2 columns]

In [39]:
employee_df.to_csv('emp.csv', index=False)

## panda from db

In [41]:
import dbms
import pandas as pd

In [45]:
user = "scott"
password = "tiger"
service_name = "orcl"
host = "10.188.193.152"
port = "1521"

In [47]:
con = dbms.connect.oracle(user, password, service_name, host, port)
cs = con.cursor()

DatabaseError: DPI-1047: 64-bit Oracle Client library cannot be loaded: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help

In [50]:
cs.execute("select * from EMPLOYEES")

columns = [x[0] for x in cs.description]

pdf = pd.DataFrame(cs.fetchall(), columns=columns)

In [51]:
pdf.head()

EMPLOYEE_ID FIRST_NAME LAST_NAME               EMAIL  PHONE_NUMBER  \
0         207        TEK       FCS  something@text.com         12345   
1         100     Steven      King               SKING  515.123.4567   
2         101      Neena   Kochhar            NKOCHHAR  515.123.4568   
3         102        Lex   De Haan             LDEHAAN  515.123.4569   
4         103        TEK       FCS             AHUNOLD  590.423.4567   

             HIRE_DATE   JOB_ID SALARY COMMISSION_PCT MANAGER_ID DEPARTMENT_ID  
0  2013-03-12 00:00:00      123  12345           0.01        123           123  
1  1987-06-17 00:00:00  AD_PRES  24000           None       None            90  
2  1989-09-21 00:00:00    AD_VP  17000           None        100            90  
3  1993-01-13 00:00:00    AD_VP  17000           None        100            90  
4  1990-01-03 00:00:00  IT_PROG   9000           None        102            60

## numpy

## 1 Dimensional Array

In [52]:
a = np.array([1, 2, 3])   # 1 dimensional array

In [55]:
a

array([1, 2, 3])

In [53]:
print(type(a))            # type of a

<class 'numpy.ndarray'>


In [54]:
print(a.shape)            # shape

(3,)


In [56]:
print(a[0], a[1], a[2])   # accessing elements

1 2 3


In [58]:
a[0] = 5                  # Change an element of the array

In [59]:
print(a)                  # Prints "[5, 2, 3]"

[5 2 3]


## 2 Dimensional Array

In [60]:
b = np.array([[1,2,3],[4,5,6]])    # Create a rank 2 array

In [61]:
print(b.shape)                     # Prints "(2, 3)"

(2, 3)


In [62]:
print(b[0, 0], b[0, 1], b[1, 0])   # accessing the elements "1 2 4"

1 2 4


## Functions to create arrays

In [63]:
a = np.zeros((2,2))   # Create an array of all zeros

In [66]:
print(a)  
#a

[[0. 0.]
 [0. 0.]]


In [71]:
b = np.ones((1,2))    # Create an array of all ones

In [72]:
print(b)              # Prints "[[ 1.  1.]]"

[[1. 1.]]


In [73]:
c = np.full((2,2), 7)  # Create a constant array

In [74]:
print(c)               

[[7 7]
 [7 7]]


In [75]:
d = np.eye(2)         # Create a 2x2 identity matrix

In [76]:
d

array([[1., 0.],
       [0., 1.]])

In [77]:
e = np.random.random((2,2))  # Create an array filled with random values

In [78]:
print(e)                     

[[0.76238964 0.35742172]
 [0.90218264 0.1755413 ]]


## Array Slicing 

In [79]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [80]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [83]:
a[0, 1]

2

In [81]:
b = a[:2, 1:3] #first 2 rows and columns 1 & 2

In [82]:
b

array([[2, 3],
       [6, 7]])

In [84]:
b[0, 0] = 77

In [85]:
b[0, 0]

77

In [86]:
b

array([[77,  3],
       [ 6,  7]])

In [87]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [90]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [91]:
row_r1 = a[1, :] #selecting 2nd row

In [92]:
row_r1

array([5, 6, 7, 8])

In [93]:
row_r2 = a[1:2, :] #alternative for the above selection

In [94]:
row_r2

array([[5, 6, 7, 8]])

In [95]:
print(row_r1, row_r1.shape)

[5 6 7 8] (4,)


In [96]:
print(row_r2, row_r2.shape)

[[5 6 7 8]] (1, 4)


In [97]:
col_r1 = a[:, 1] #selecting a column

In [98]:
col_r1

array([ 2,  6, 10])

In [99]:
col_r2 = a[:, 1:2]

In [100]:
col_r2

array([[ 2],
       [ 6],
       [10]])

In [101]:
print(col_r1, col_r1.shape)

[ 2  6 10] (3,)


In [102]:
print(col_r2, col_r2.shape)  

[[ 2]
 [ 6]
 [10]] (3, 1)


## Integer Indexing

In [103]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [104]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [105]:
a[[0, 1, 2], [0, 1, 0]]

array([1, 4, 5])

In [107]:
np.array([a[0, 0], a[1, 1], a[2, 0]])

array([1, 4, 5])

## Boolean array indexing

In [114]:
a = np.array([[1,2], [3, 4], [5, 6]])

In [115]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [116]:
bool_idx = (a > 2)

In [117]:
bool_idx

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [118]:
a[bool_idx]

array([3, 4, 5, 6])

In [119]:
a[a > 2]

array([3, 4, 5, 6])

## Array math

In [120]:
x = np.array([[1,2],[3,4]], dtype=np.float64)

In [121]:
x

array([[1., 2.],
       [3., 4.]])

In [122]:
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [123]:
y

array([[5., 6.],
       [7., 8.]])

In [124]:
y.dtype

dtype('float64')

In [125]:
x + y #Element wise sum

array([[ 6.,  8.],
       [10., 12.]])

In [126]:
x - y #Element wise subtraction

array([[-4., -4.],
       [-4., -4.]])

In [127]:
np.subtract(x, y)

array([[-4., -4.],
       [-4., -4.]])

In [128]:
np.add(x, y)

array([[ 6.,  8.],
       [10., 12.]])

In [129]:
x * y #Element wise product

array([[ 5., 12.],
       [21., 32.]])

In [130]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [131]:
print(x / y) #Elementwise division

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [132]:
np.divide(x, y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [133]:
np.sqrt(x) #Elementwise suare root

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

## Inner product

In [134]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [135]:
x

array([[1, 2],
       [3, 4]])

In [136]:
y

array([[5, 6],
       [7, 8]])

In [137]:
v

array([ 9, 10])

In [138]:
w

array([11, 12])

In [139]:
v.dot(w)
#np.dot(v, w)

219

In [140]:
x.dot(v)
#np.dot(x, v)

array([29, 67])

In [141]:
x.dot(y)

array([[19, 22],
       [43, 50]])

## Numpy in built functions

In [142]:
np.sum(x)

10

In [143]:
x

array([[1, 2],
       [3, 4]])

In [144]:
np.sum(x, axis=0)

array([4, 6])

In [145]:
np.sum(x, axis=1)

array([3, 7])

In [146]:
x.T #transpose

array([[1, 3],
       [2, 4]])

In [149]:
v = np.array([1,2,3]) #no effect on 1 dimensional array
v

array([1, 2, 3])

In [150]:
v.T

array([1, 2, 3])

In [151]:
np.reshape(v, (3,1))

array([[1],
       [2],
       [3]])